import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';


import Header from '../components/header';
import Footer from '../components/footer';

import image1 from '../assets/images/image 1.png';
import image2 from '../assets/images/image 2.png';

export default function Home() {
  return (
    <div className='min-h-screen flex flex-col justify-between'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className='flex flex-col items-center text-center'>
        <h1 className='text-3xl font-bold'>Bienvenido</h1>
        <p className='text-3xl mb-3'>Selecciona una opción</p>
        <div className='flex flex-col md:flex-row justify-around px-2'>
          <Link href="/thickness">
            <a>
              <div className='flex flex-col items-center mb-8 md:mb-3 text-3xl hover:underline'>
                <Image height={300}  src={image1} className="object-cover"/>
                <h2>Cálculo de Grosor Final</h2>
              </div>
            </a>
          </Link>
          <Link href="/time">
            <a>
              <div className='flex flex-col items-center mb-8 md:mb-3 text-3xl hover:underline'>
                <Image  height={300}  src={image2} className="object-cover"/>
                <h2>Cálculo de tiempo de Oxidación</h2>
              </div>
            </a>
          </Link>
        </div>
      </main>

      <Footer/>
    </div>
  )
}
